Merge branch 'develop' into coreMIS

diff --git a/.github/workflows/ci_assembly.yml b/.github/workflows/ci_assembly.yml
--- a/.github/workflows/ci_assembly.yml
+++ b/.github/workflows/ci_assembly.yml
@@ -11,32 +11,32 @@ on:
 
 jobs:
   ci_assembly:
-    runs-on: ubuntu-20.04
+    runs-on: ubuntu-latest
 
     services:
-      mssql:
-        image: mcr.microsoft.com/mssql/server:2017-latest
-        env:
-          ACCEPT_EULA: Y
-          SA_PASSWORD: GitHub999
-        ports:
-          - 1433:1433
-        # this health-cmd needed because the mssql container does not provide a health check
-        options: >-
-          --health-interval=10s
-          --health-timeout=5s
-          --health-start-period=10s
-          --health-retries=10
-          --health-cmd="/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P ${SA_PASSWORD} -Q 'SELECT 1' || exit 1"
-      
+      # mssql:
+      #   image: mcr.microsoft.com/mssql/server:2022-CU14-ubuntu-22.04
+      #   env:
+      #     ACCEPT_EULA: Y
+      #     SA_PASSWORD: YourStrong!Passw0rd
+      #   ports:
+      #     - 1433:1433
+      #   options:           
+      #      --health-interval=10s 
+      #      --health-interval=20s 
+      #      --health-timeout=3s 
+      #      --health-start-period=10s 
+      #      --health-retries=10 
+      #      --health-cmd="sqlcmd -S localhost -U sa -P ${SA_PASSWORD} -Q 'SELECT 1' || exit 1"
+ 
       pgsql:
-        image: postgres
+        image: ghcr.io/openimis/openimis-pgsql:develop
         env:
           DB_HOST: localhost
           DB_PORT: 5432
-          POSTGRES_DB: imis
+          POSTGRES_DB: test_imis
           POSTGRES_USER: postgres
-          POSTGRES_PASSWORD: GitHub999
+          POSTGRES_PASSWORD: YourStrong!Passw0rd
         ports:
           - 5432:5432
         options: >-
@@ -44,16 +44,31 @@ jobs:
           --health-interval 10s
           --health-timeout 5s
           --health-retries 10
+      opensearch:
+        image: opensearchproject/opensearch:latest
+        ports:
+          - 9200:9200
+        env:
+          discovery.type: single-node
+          cluster.name: my_opensearch_local
+          http.port: 9200
+          plugins.security.ssl.http.enabled: false
+          OPENSEARCH_INITIAL_ADMIN_PASSWORD: B9wc9VrqX7pY
+        options: >-
+          --health-cmd "curl -f -u admin:${OPENSEARCH_INITIAL_ADMIN_PASSWORD} http://localhost:9200/_cluster/health || exit 1"
+          --health-interval 10s
+          --health-timeout 5s
+          --health-retries 10
     steps:
-      - uses: actions/checkout@v2
+      - uses: actions/checkout@v4
 
       - name: Set up Python 3.10
-        uses: actions/setup-python@v2
+        uses: actions/setup-python@v5
         with:
           python-version: "3.10"
 
       - name: Cache dependencies
-        uses: actions/cache@v2
+        uses: actions/cache@v4
         with:
           path: ~/.cache/pip
           key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
@@ -81,56 +96,52 @@ jobs:
       - name: Initialize PSQL
         run: |
           export DB_NAME_TEST="test_$DB_NAME"
-
           if [ ${GITHUB_REF##*/} = "main" ]; then export DBBRANCH="main"; else export DBBRANCH="develop"; fi
           echo "Branch ${GITHUB_REF##*/}, usign ${DBBRANCH} branch for database"
           git clone  --depth=1 --branch=$DBBRANCH https://github.com/openimis/database_postgresql.git ./sql_psql
-
+          sudo bash ./sql_psql/install_postgres_json_schema_extension.sh
           echo 'set search_path to public' >> ~/.psqlrc
-          PGPASSWORD=GitHub999 psql -U $DB_USER -h $DB_HOST -c "DROP DATABASE IF EXISTS \"$DB_NAME_TEST\";"
-          PGPASSWORD=GitHub999 psql -U $DB_USER -h $DB_HOST -c "CREATE DATABASE \"$DB_NAME_TEST\";"
-
-          PGPASSWORD=GitHub999 psql -U $DB_USER -h $DB_HOST -d $DB_NAME_TEST -f  ./sql_psql/database\ scripts/00_dump.sql | grep . | uniq -c
-          PGPASSWORD=GitHub999 psql -U $DB_USER -h $DB_HOST -d $DB_NAME_TEST -f  ./sql_psql/database\ scripts/02_aux_functions.sql | grep . | uniq -c
-          PGPASSWORD=GitHub999 psql -U $DB_USER -h $DB_HOST -d $DB_NAME_TEST -f  ./sql_psql/database\ scripts/03_views.sql | grep . | uniq -c
-          PGPASSWORD=GitHub999 psql -U $DB_USER -h $DB_HOST -d $DB_NAME_TEST -f  ./sql_psql/database\ scripts/04_functions.sql | grep . | uniq -c
-          PGPASSWORD=GitHub999 psql -U $DB_USER -h $DB_HOST -d $DB_NAME_TEST -f  ./sql_psql/database\ scripts/05_stored_procs.sql | grep . | uniq -c
-          PGPASSWORD=GitHub999 psql -U $DB_USER -h $DB_HOST -d $DB_NAME_TEST -f  ./sql_psql/database\ scripts/demo_db.sql | grep . | uniq -c
-
+          PGPASSWORD=YourStrong!Passw0rd psql -U $DB_USER -h $DB_HOST -d $DB_NAME_TEST -f  ./sql_psql/database\ scripts/json_schema_extension.sql | grep . | uniq -c
         env:
           DB_HOST: localhost
           DB_PORT: 5432
           DB_NAME: imis
           DB_USER: postgres
-          DB_PASSWORD: GitHub999
+          DB_PASSWORD: YourStrong!Passw0rd
 
-      - name: Initialize MSSQL
-        run: |
-          export DB_NAME_TEST="test_$DB_NAME"
+      # - name: Initialize MSSQL
+      #   run: |
+      #     export DB_NAME_TEST="test_$DB_NAME"
           
-          if [ ${GITHUB_REF##*/} = "main" ]; then export DBBRANCH="main"; else export DBBRANCH="develop"; fi
-          echo "Branch ${GITHUB_REF##*/}, usign ${DBBRANCH} branch for database"
-          git clone --depth=1 --branch=$DBBRANCH https://github.com/openimis/database_ms_sqlserver.git ./sql_mssql
-          cd sql_mssql/ && bash concatenate_files.sh && cd ..
+      #     if [ ${GITHUB_REF##*/} = "main" ]; then export DBBRANCH="main"; else export DBBRANCH="develop"; fi
+      #     echo "Branch ${GITHUB_REF##*/}, usign ${DBBRANCH} branch for database"
+      #     git clone --depth=1 --branch=$DBBRANCH https://github.com/openimis/database_ms_sqlserver.git ./sql_mssql
+      #     cd sql_mssql/ && bash concatenate_files.sh && cd ..
 
-          curl https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -
-          curl https://packages.microsoft.com/config/ubuntu/20.04/prod.list | sudo tee /etc/apt/sources.list.d/msprod.list
-          sudo apt-get update
-          sudo apt-get install mssql-tools unixodbc-dev
-          
-          #Main db has to exists for tests to run correctly, psql container creates empty main db by default
-          /opt/mssql-tools/bin/sqlcmd -S $DB_HOST -U $DB_USER -P $DB_PASSWORD -Q "DROP DATABASE IF EXISTS $DB_NAME"
-          /opt/mssql-tools/bin/sqlcmd -S $DB_HOST -U $DB_USER -P $DB_PASSWORD -Q "CREATE DATABASE $DB_NAME"
+      #     curl https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -
+      #     curl https://packages.microsoft.com/config/ubuntu/24.04/prod.list | sudo tee /etc/apt/sources.list.d/msprod.list
+      #     sudo apt-get update
+      #     sudo apt-get install -y --allow-downgrades --allow-remove-essential --allow-change-held-packages mssql-tools18 unixodbc-dev
+      #     echo "Waiting for SQL Server to be fully operational..."
+      #     until /opt/mssql-tools18/bin/sqlcmd -S localhost -U $DB_USER -P $DB_PASSWORD -Q "SELECT @@VERSION" > /dev/null 2>&1
+      #     do
+      #       echo "SQL Server is still initializing. Waiting..."
+      #       sleep 5
+      #     done
+      #     echo "SQL Server is now operational."
+      #     #Main db has to exists for tests to run correctly, psql container creates empty main db by default
+      #     /opt/mssql-tools18/bin/sqlcmd -S $DB_HOST -U $DB_USER -P $DB_PASSWORD -Q "DROP DATABASE IF EXISTS $DB_NAME"
+      #     /opt/mssql-tools18/bin/sqlcmd -S $DB_HOST -U $DB_USER -P $DB_PASSWORD -Q "CREATE DATABASE $DB_NAME"
 
-          /opt/mssql-tools/bin/sqlcmd -S $DB_HOST -U $DB_USER -P $DB_PASSWORD -Q "DROP DATABASE IF EXISTS $DB_NAME_TEST"
-          /opt/mssql-tools/bin/sqlcmd -S $DB_HOST -U $DB_USER -P $DB_PASSWORD -Q "CREATE DATABASE $DB_NAME_TEST"
-          /opt/mssql-tools/bin/sqlcmd -S $DB_HOST -U $DB_USER -P $DB_PASSWORD -d $DB_NAME_TEST -i ./sql_mssql/output/fullDemoDatabase.sql | grep . | uniq -c
-        env:
-          DB_HOST: localhost
-          DB_PORT: 1433
-          DB_NAME: imis
-          DB_USER: sa
-          DB_PASSWORD: GitHub999
+      #     /opt/mssql-tools18/bin/sqlcmd -S $DB_HOST -U $DB_USER -P $DB_PASSWORD -Q "DROP DATABASE IF EXISTS $DB_NAME_TEST"
+      #     /opt/mssql-tools18/bin/sqlcmd -S $DB_HOST -U $DB_USER -P $DB_PASSWORD -Q "CREATE DATABASE $DB_NAME_TEST"
+      #     /opt/mssql-tools18/bin/sqlcmd -S $DB_HOST -U $DB_USER -P $DB_PASSWORD -d $DB_NAME_TEST -i ./sql_mssql/output/fullDemoDatabase.sql | grep . | uniq -c
+      #   env:
+      #     DB_HOST: localhost
+      #     DB_PORT: 1433
+      #     DB_NAME: imis
+      #     DB_USER: sa
+      #     DB_PASSWORD: YourStrong!Passw0rd
 
       - name: Django tests PSQL
         working-directory: ./openIMIS
@@ -145,38 +156,49 @@ jobs:
         env:
           SECRET_KEY: secret
           MODE: DEV
-          DB_ENGINE: django.db.backends.postgresql
+          DB_DEFAULT: postgresql
+          CELERY_BROKER_URL: "memory://openIMIS-test//"
+          CELERY_RESULT_BACKEND: "cache+memory://openIMIS-test//"
           #DJANGO_SETTINGS_MODULE: hat.settings
           DB_HOST: localhost
           DB_PORT: 5432
           DB_NAME: imis
           DB_USER: postgres
-          DB_PASSWORD: GitHub999
+          DB_PASSWORD: YourStrong!Passw0rd
           #DEV_SERVER: true
           SITE_ROOT: api
           CI_EXCLUDED_MODULE: ${{ vars.CI_EXCLUDED_MODULE }}
+          OPENSEARCH_ADMIN: admin
+          OPENSEARCH_PASSWORD: B9wc9VrqX7pY
+          OPEN_SEARCH_HTTP_PORT: 9200
+          OPENSEARCH_HOSTS: "localhost:9200"
 
-      - name: Django tests MSSQL
-        working-directory: ./openIMIS
-        # Run the tests regardless if previous steps failed (if setup fails the tests should crash instantly)
-        if: success() || failure()
-        run: |
-          python -V
-          export MODULES=$(jq -r '(.modules[].name)' ../openimis.json | xargs)
-          MODULES=$(echo "$MODULES" | sed -E "s/\b$(echo "${CI_EXCLUDED_MODULE// /\\b|\\b}")\b/ /g" | xargs)
-          echo $MODULES
-          python manage.py test --debug-mode --timing --keepdb $MODULES
-        env:
-          SECRET_KEY: secret
-          MODE: DEV
-          DB_ENGINE: mssql
-          #DJANGO_SETTINGS_MODULE: hat.settings
-          DB_HOST: localhost
-          DB_PORT: 1433
-          DB_NAME: imis
-          DB_USER: sa
-          DB_PASSWORD: GitHub999
-          #DEV_SERVER: true
-          SITE_ROOT: api
-          #REMOTE_USER_AUTHENTICATION: False
-          CI_EXCLUDED_MODULE: ${{ vars.CI_EXCLUDED_MODULE }}
+      # - name: Django tests MSSQL
+      #   working-directory: ./openIMIS
+      #   # Run the tests regardless if previous steps failed (if setup fails the tests should crash instantly)
+      #   if: success() || failure()
+      #   run: |
+      #     python -V
+      #     export MODULES=$(jq -r '(.modules[].name)' ../openimis.json | xargs)
+      #     MODULES=$(echo "$MODULES" | sed -E "s/\b$(echo "${CI_EXCLUDED_MODULE// /\\b|\\b}")\b/ /g" | xargs)
+      #     echo $MODULES
+      #     python manage.py test --debug-mode --timing --keepdb $MODULES
+      #   env:
+      #     SECRET_KEY: secret
+      #     MODE: DEV
+      #     DB_DEFAULT: mssql
+      #     CELERY_BROKER_URL: "memory://openIMIS-test//"
+      #     CELERY_RESULT_BACKEND: "cache+memory://openIMIS-test//"
+      #     #DJANGO_SETTINGS_MODULE: hat.settings
+      #     DB_HOST: localhost
+      #     DB_PORT: 1433
+      #     DB_NAME: imis
+      #     DB_USER: sa
+      #     DB_PASSWORD: YourStrong!Passw0rd
+      #     #DEV_SERVER: true
+      #     SITE_ROOT: api
+      #     #REMOTE_USER_AUTHENTICATION: False
+      #     CI_EXCLUDED_MODULE: ${{ vars.CI_EXCLUDED_MODULE }}
+      #     OPENSEARCH_DSL_AUTOSYNC: False
+      #     OPEN_SEARCH_HTTP_PORT: 9200
+      #     OPENSEARCH_HOSTS: "localhost:9200"
diff --git a/.github/workflows/ci_module.yml b/.github/workflows/ci_module.yml
--- a/.github/workflows/ci_module.yml
+++ b/.github/workflows/ci_module.yml
@@ -41,27 +41,51 @@ on:
 jobs:
   build_backend:
     name: Build Backend
-    runs-on: ubuntu-20.04
+    runs-on: ubuntu-24.04
     steps:
       - name: Set up Python 3.10
-        uses: actions/setup-python@v2
+        uses: actions/setup-python@v5
         with:
           python-version: '3.10'
 
       - name: Pull openIMIS Backend
         run: |
-          rm ./openimis -rf
-          git clone --depth=1 --branch=${{ inputs.branchName }} https://github.com/openimis/openimis-be_py.git ./openimis
+          # Determine the target branch
+          if [ "${{ github.event_name }}" == "pull_request" ]; then
+            TARGET_BRANCH="${{ github.event.pull_request.base.ref }}"
+          else
+            TARGET_BRANCH="${{ github.event.ref }}"
+            TARGET_BRANCH=${TARGET_BRANCH#refs/heads/}
+          fi
+      
+          # Use 'develop' as fallback if TARGET_BRANCH is empty or not a release branch
+          if [[ -z "$TARGET_BRANCH" ]]; then
+            TARGET_BRANCH="develop"
+          fi
+      
+          echo "Target branch: $TARGET_BRANCH"
+      
+          # Clone the repository
+          rm -rf ./openimis
+          git clone --depth=1 --branch=$TARGET_BRANCH https://github.com/openimis/openimis-be_py.git ./openimis || {
+            echo "Failed to clone $TARGET_BRANCH, falling back to develop"
+            git clone --depth=1 --branch=develop https://github.com/openimis/openimis-be_py.git ./openimis
+          }
+      
+          # Verify the cloned branch
+          cd ./openimis
+          CLONED_BRANCH=$(git rev-parse --abbrev-ref HEAD)
+          echo "Cloned branch: $CLONED_BRANCH"
 
       - name: Copy Current branch
-        uses: actions/checkout@v2
+        uses: actions/checkout@v4
         with:
           # Disabling shallow clone is recommended for improving relevancy of reporting
           fetch-depth: 0
           path: './current-module'
 
       - name: Cache dependencies
-        uses: actions/cache@v2
+        uses: actions/cache@v4
         with:
           path: ~/.cache/pip
           key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
@@ -119,128 +143,34 @@ jobs:
         with:
           name: code-artifacts
           path: openimis.tar.gz
-  ci_module_mssql_tests:
-    name: Run Module Tests (MSSQL)
-    runs-on: ubuntu-20.04
-    needs: build_backend
-    services:
-      mssql:
-        image: mcr.microsoft.com/mssql/server:2017-latest
-        env:
-          ACCEPT_EULA: Y
-          SA_PASSWORD: GitHub999
-        ports:
-          - 1433:1433
-        # this health-cmd needed because the mssql container does not provide a health check
-        options: >-
-          --health-interval=10s
-          --health-timeout=5s
-          --health-start-period=10s
-          --health-retries=10
-          --health-cmd="/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P ${SA_PASSWORD} -Q 'SELECT 1' || exit 1"
-    steps:
-      - name: Set up Python 3.10
-        uses: actions/setup-python@v2
-        with:
-          python-version: '3.10'
-
-      - name: Download site-packages artifact
-        uses: actions/download-artifact@v4
-        with:
-          name: site-packages
-          path: /tmp/
-
-      - name: Locate site-packages
-        run: |
-          SITE_PACKAGES=$(python -c "from distutils.sysconfig import get_python_lib; print(get_python_lib())")
-          echo "SITE_PACKAGES=$SITE_PACKAGES" >> $GITHUB_ENV
-
-      - name: Download site-packages artifact
-        uses: actions/download-artifact@v4
-        with:
-          name: code-artifacts
-          path: /tmp/
-
-      - name: Decompress artifacts
-        run: |
-          sudo tar -xzf /tmp/site-packages.tar.gz -C ${{ env.SITE_PACKAGES }}
-          sudo tar -xzf /tmp/openimis.tar.gz -C .
-      - name: Initialize MSSQL
-        run: |
-          export DB_NAME_TEST="test_$DB_NAME"
-          
-          if [ ${GITHUB_REF##*/} = "main" ]; then export DBBRANCH="main"; else export DBBRANCH="develop"; fi
-          echo "Branch ${GITHUB_REF##*/}, usign ${DBBRANCH} branch for database"
-          git clone --depth=1 --branch=$DBBRANCH https://github.com/openimis/database_ms_sqlserver.git ./sql_mssql
-          cd sql_mssql/ && bash concatenate_files.sh && cd ..
-
-          curl https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -
-          curl https://packages.microsoft.com/config/ubuntu/20.04/prod.list | sudo tee /etc/apt/sources.list.d/msprod.list
-          sudo apt-get update
-          sudo apt-get install mssql-tools unixodbc-dev
-          
-          #Main db has to exists for tests to run correctly, psql container creates empty main db by default
-          /opt/mssql-tools/bin/sqlcmd -S $DB_HOST -U $DB_USER -P $DB_PASSWORD -Q "DROP DATABASE IF EXISTS $DB_NAME"
-          /opt/mssql-tools/bin/sqlcmd -S $DB_HOST -U $DB_USER -P $DB_PASSWORD -Q "CREATE DATABASE $DB_NAME"
-
-          /opt/mssql-tools/bin/sqlcmd -S $DB_HOST -U $DB_USER -P $DB_PASSWORD -Q "DROP DATABASE IF EXISTS $DB_NAME_TEST"
-          /opt/mssql-tools/bin/sqlcmd -S $DB_HOST -U $DB_USER -P $DB_PASSWORD -Q "CREATE DATABASE $DB_NAME_TEST"
-          /opt/mssql-tools/bin/sqlcmd -S $DB_HOST -U $DB_USER -P $DB_PASSWORD -d $DB_NAME_TEST -i ./sql_mssql/output/fullDemoDatabase.sql | grep . | uniq -c
-        env:
-          DB_HOST: localhost
-          DB_PORT: 1433
-          DB_NAME: imis
-          DB_USER: sa
-          DB_PASSWORD: GitHub999
-      - name: Cache dependencies
-        uses: actions/cache@v2
-        with:
-          path: ~/.cache/pip
-          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
-          restore-keys: |
-            ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
-            ${{ runner.os }}-pip-
-            ${{ runner.os }}-
-      - name: Django tests MSSQL Module
-        working-directory: ./openimis/openIMIS
-        # Run the tests regardless if previous steps failed (if setup fails the tests should crash instantly)
-        if: success() || failure()
-        run: |
-          python -V
-          export MODULES=$(jq -r '(.modules[].name)' ../openimis.json | xargs)
-          MODULES=$(echo "$MODULES" | sed -E "s/\b$(echo "${CI_EXCLUDED_MODULE// /\\b|\\b}")\b/ /g" | xargs)
-          
-          export MODULE_NAME="$(echo $GITHUB_REPOSITORY | sed 's#^openimis/openimis-be-\(.*\)_py$#\1#')"
-          echo "MODULE_NAME=$MODULE_NAME" >> $GITHUB_ENV
-          
-          python manage.py test --debug-mode --timing --keepdb $MODULE_NAME
-        env:
-          SECRET_KEY: secret
-          DB_ENGINE: mssql
-          #DJANGO_SETTINGS_MODULE: hat.settings
-          DB_HOST: localhost
-          DB_PORT: 1433
-          DB_NAME: imis
-          DB_USER: sa
-          DB_PASSWORD: GitHub999
-          #DEV_SERVER: true
-          SITE_ROOT: api
-          #REMOTE_USER_AUTHENTICATION: False
-          CI_EXCLUDED_MODULE: ${{ vars.CI_EXCLUDED_MODULE }}
-          MODE: DEV
   ci_module_psql_test_module_only:
     name: Run Module Tests (PSQL)
-    runs-on: ubuntu-20.04
+    runs-on: ubuntu-24.04
     needs: build_backend
     services:
+      opensearch:
+        image: opensearchproject/opensearch:latest
+        ports:
+          - 9200:9200
+        env:
+          discovery.type: single-node
+          cluster.name: my_opensearch_local
+          http.port: 9200
+          plugins.security.ssl.http.enabled: false
+          OPENSEARCH_INITIAL_ADMIN_PASSWORD: B9wc9VrqX7pY
+        options: >-
+          --health-cmd "curl -f -u admin:${OPENSEARCH_INITIAL_ADMIN_PASSWORD} http://localhost:9200/_cluster/health || exit 1"
+          --health-interval 10s
+          --health-timeout 5s
+          --health-retries 10
       pgsql:
-        image: postgres
+        image: ghcr.io/openimis/openimis-pgsql:develop
         env:
           DB_HOST: localhost
           DB_PORT: 5432
           POSTGRES_DB: test_imis
           POSTGRES_USER: postgres
-          POSTGRES_PASSWORD: GitHub999
+          POSTGRES_PASSWORD: YourStrong!Passw0rd
         ports:
           - 5432:5432
         options: >-
@@ -250,7 +180,7 @@ jobs:
           --health-retries 10
     steps:
       - name: Set up Python 3.10
-        uses: actions/setup-python@v2
+        uses: actions/setup-python@v5
         with:
           python-version: '3.10'
 
@@ -278,73 +208,61 @@ jobs:
       - name: Initialize PSQL
         run: |
           export DB_NAME_TEST="test_$DB_NAME"
-
           if [ ${GITHUB_REF##*/} = "main" ]; then export DBBRANCH="main"; else export DBBRANCH="develop"; fi
           echo "Branch ${GITHUB_REF##*/}, usign ${DBBRANCH} branch for database"
           git clone  --depth=1 --branch=$DBBRANCH https://github.com/openimis/database_postgresql.git ./sql_psql
-
+          sudo bash ./sql_psql/install_postgres_json_schema_extension.sh
           echo 'set search_path to public' >> ~/.psqlrc
-          PGPASSWORD=GitHub999 psql -U $DB_USER -h $DB_HOST -c "DROP DATABASE IF EXISTS \"$DB_NAME_TEST\";"
-          PGPASSWORD=GitHub999 psql -U $DB_USER -h $DB_HOST -c "CREATE DATABASE \"$DB_NAME_TEST\";"
-
-          PGPASSWORD=GitHub999 psql -U $DB_USER -h $DB_HOST -d $DB_NAME_TEST -f  ./sql_psql/database\ scripts/00_dump.sql | grep . | uniq -c
-          PGPASSWORD=GitHub999 psql -U $DB_USER -h $DB_HOST -d $DB_NAME_TEST -f  ./sql_psql/database\ scripts/02_aux_functions.sql | grep . | uniq -c
-          PGPASSWORD=GitHub999 psql -U $DB_USER -h $DB_HOST -d $DB_NAME_TEST -f  ./sql_psql/database\ scripts/03_views.sql | grep . | uniq -c
-          PGPASSWORD=GitHub999 psql -U $DB_USER -h $DB_HOST -d $DB_NAME_TEST -f  ./sql_psql/database\ scripts/04_functions.sql | grep . | uniq -c
-          PGPASSWORD=GitHub999 psql -U $DB_USER -h $DB_HOST -d $DB_NAME_TEST -f  ./sql_psql/database\ scripts/05_stored_procs.sql | grep . | uniq -c
-          PGPASSWORD=GitHub999 psql -U $DB_USER -h $DB_HOST -d $DB_NAME_TEST -f  ./sql_psql/database\ scripts/demo_db.sql | grep . | uniq -c
-
+          PGPASSWORD=YourStrong!Passw0rd psql -U $DB_USER -h $DB_HOST -d $DB_NAME_TEST -f  ./sql_psql/database\ scripts/json_schema_extension.sql | grep . | uniq -c
         env:
           DB_HOST: localhost
           DB_PORT: 5432
           DB_NAME: imis
           DB_USER: postgres
-          DB_PASSWORD: GitHub999
+          DB_PASSWORD: YourStrong!Passw0rd
+      
+      
       - name: Django tests PSQL
         working-directory: ./openimis/openIMIS
+
         # Run the tests regardless if previous steps failed (if setup fails the tests should crash instantly)
         if: success() || failure()
         run: |
-          export DB_NAME_TEST="test_$DB_NAME"
-          
-          export MODULES=$(jq -r '(.modules[].name)' ../openimis.json | xargs)
-
-          # Remove some module from MODULES
-          MODULES=$(echo "$MODULES" | sed -E "s/\b$(echo "${CI_EXCLUDED_MODULE// /\\b|\\b}")\b/ /g" | xargs)
-          echo $MODULES
-          
-          DB_NAME=test_imis python manage.py migrate
-          # Generate sonar report 
+          python -V
           export MODULE_NAME="$(echo $GITHUB_REPOSITORY | sed 's#^openimis/openimis-be-\(.*\)_py$#\1#')"
-
-          # This has to exit 0, or report is not generated 
-          python -m coverage run --omit=*/migrations/* ./manage.py test --keepdb $MODULE_NAME
+          python manage.py test --keepdb $MODULE_NAME
         env:
           SECRET_KEY: secret
-          DB_ENGINE: django.db.backends.postgresql
+          MODE: DEV
+          DB_DEFAULT: postgresql
+          CELERY_BROKER_URL: "memory://openIMIS-test//"
+          CELERY_RESULT_BACKEND: "cache+memory://openIMIS-test//"
           #DJANGO_SETTINGS_MODULE: hat.settings
           DB_HOST: localhost
           DB_PORT: 5432
           DB_NAME: imis
           DB_USER: postgres
-          DB_PASSWORD: GitHub999
+          DB_PASSWORD: YourStrong!Passw0rd
           #DEV_SERVER: true
           SITE_ROOT: api
           CI_EXCLUDED_MODULE: ${{ vars.CI_EXCLUDED_MODULE }}
-          MODE: DEV
+          OPENSEARCH_ADMIN: admin
+          OPENSEARCH_PASSWORD: B9wc9VrqX7pY
+          OPEN_SEARCH_HTTP_PORT: 9200
+          OPENSEARCH_HOSTS: "localhost:9200"
   ci_module_psql_test:
     name: Run All Tests (PSQL)
-    runs-on: ubuntu-20.04
+    runs-on: ubuntu-24.04
     needs: build_backend
     services:
       pgsql:
-        image: postgres
+        image: ghcr.io/openimis/openimis-pgsql:develop
         env:
           DB_HOST: localhost
           DB_PORT: 5432
-          POSTGRES_DB: imis
+          POSTGRES_DB: test_imis
           POSTGRES_USER: postgres
-          POSTGRES_PASSWORD: GitHub999
+          POSTGRES_PASSWORD: YourStrong!Passw0rd
         ports:
           - 5432:5432
         options: >-
@@ -354,7 +272,7 @@ jobs:
           --health-retries 10
     steps:
       - name: Set up Python 3.10
-        uses: actions/setup-python@v2
+        uses: actions/setup-python@v5
         with:
           python-version: '3.10'
 
@@ -382,29 +300,20 @@ jobs:
       - name: Initialize PSQL
         run: |
           export DB_NAME_TEST="test_$DB_NAME"
-          
           if [ ${GITHUB_REF##*/} = "main" ]; then export DBBRANCH="main"; else export DBBRANCH="develop"; fi
           echo "Branch ${GITHUB_REF##*/}, usign ${DBBRANCH} branch for database"
           git clone  --depth=1 --branch=$DBBRANCH https://github.com/openimis/database_postgresql.git ./sql_psql
-          
+          sudo bash ./sql_psql/install_postgres_json_schema_extension.sh
           echo 'set search_path to public' >> ~/.psqlrc
-          PGPASSWORD=GitHub999 psql -U $DB_USER -h $DB_HOST -c "DROP DATABASE IF EXISTS \"$DB_NAME_TEST\";"
-          PGPASSWORD=GitHub999 psql -U $DB_USER -h $DB_HOST -c "CREATE DATABASE \"$DB_NAME_TEST\";"
-          
-          PGPASSWORD=GitHub999 psql -U $DB_USER -h $DB_HOST -d $DB_NAME_TEST -f  ./sql_psql/database\ scripts/00_dump.sql | grep . | uniq -c
-          PGPASSWORD=GitHub999 psql -U $DB_USER -h $DB_HOST -d $DB_NAME_TEST -f  ./sql_psql/database\ scripts/02_aux_functions.sql | grep . | uniq -c
-          PGPASSWORD=GitHub999 psql -U $DB_USER -h $DB_HOST -d $DB_NAME_TEST -f  ./sql_psql/database\ scripts/03_views.sql | grep . | uniq -c
-          PGPASSWORD=GitHub999 psql -U $DB_USER -h $DB_HOST -d $DB_NAME_TEST -f  ./sql_psql/database\ scripts/04_functions.sql | grep . | uniq -c
-          PGPASSWORD=GitHub999 psql -U $DB_USER -h $DB_HOST -d $DB_NAME_TEST -f  ./sql_psql/database\ scripts/05_stored_procs.sql | grep . | uniq -c
-          PGPASSWORD=GitHub999 psql -U $DB_USER -h $DB_HOST -d $DB_NAME_TEST -f  ./sql_psql/database\ scripts/demo_db.sql | grep . | uniq -c
-
+          PGPASSWORD=YourStrong!Passw0rd psql -U $DB_USER -h $DB_HOST -d $DB_NAME_TEST -f  ./sql_psql/database\ scripts/json_schema_extension.sql | grep . | uniq -c
         env:
           DB_HOST: localhost
           DB_PORT: 5432
           DB_NAME: imis
           DB_USER: postgres
-          DB_PASSWORD: GitHub999
-          MODE: DEV
+          DB_PASSWORD: YourStrong!Passw0rd
+      
+      
       - name: Django tests PSQL
         working-directory: ./openimis/openIMIS
         # Run the tests regardless if previous steps failed (if setup fails the tests should crash instantly)
@@ -412,29 +321,29 @@ jobs:
         run: |
           python -V
           export MODULES=$(jq -r '(.modules[].name)' ../openimis.json | xargs)
-
-          # Remove some module from MODULES
           MODULES=$(echo "$MODULES" | sed -E "s/\b$(echo "${CI_EXCLUDED_MODULE// /\\b|\\b}")\b/ /g" | xargs)
           echo $MODULES
-          # Generate sonar report 
-          export MODULE_NAME="$(echo $GITHUB_REPOSITORY | sed 's#^openimis/openimis-be-\(.*\)_py$#\1#')"
-          
-          # This has to exit 0, or report is not generated 
-          DB_NAME=test_imis python manage.py migrate
-          python -m coverage run --source=$MODULE_NAME --omit=*/migrations/* ./manage.py test --keepdb $MODULES
+          python manage.py test --keepdb $MODULES
         env:
           SECRET_KEY: secret
-          DB_ENGINE: django.db.backends.postgresql
+          MODE: DEV
+          DB_DEFAULT: postgresql
+          CELERY_BROKER_URL: "memory://openIMIS-test//"
+          CELERY_RESULT_BACKEND: "cache+memory://openIMIS-test//"
           #DJANGO_SETTINGS_MODULE: hat.settings
           DB_HOST: localhost
           DB_PORT: 5432
           DB_NAME: imis
           DB_USER: postgres
-          DB_PASSWORD: GitHub999
+          DB_PASSWORD: YourStrong!Passw0rd
           #DEV_SERVER: true
           SITE_ROOT: api
           CI_EXCLUDED_MODULE: ${{ vars.CI_EXCLUDED_MODULE }}
-          MODE: DEV
+          OPENSEARCH_ADMIN: admin
+          OPENSEARCH_PASSWORD: B9wc9VrqX7pY
+          OPEN_SEARCH_HTTP_PORT: 9200
+          OPENSEARCH_HOSTS: "localhost:9200"
+          OPENSEARCH_DSL_AUTOSYNC: False
       - name: Generate Coverage Report
         if: always()
         working-directory: ./openimis/openIMIS
@@ -456,11 +365,11 @@ jobs:
           path: ./openimis/openIMIS/coverage
   flake-8-linter:
     name: Run flake8 check
-    runs-on: ubuntu-20.04
+    runs-on: ubuntu-24.04
     needs: build_backend
     steps:
       - name: Set up Python 3.10
-        uses: actions/setup-python@v2
+        uses: actions/setup-python@v5
         with:
           python-version: '3.10'
       - name: Download site-packages artifact
@@ -492,10 +401,10 @@ jobs:
           # Flake8 Report
           export MODULE_NAME="$(echo $GITHUB_REPOSITORY | sed 's#^openimis/openimis-be-\(.*\)_py$#\1#')"
           MOD_DIR="../current-module/$MODULE_NAME"
-          python -m flake8 --output-file=flake8-report.txt $MOD_DIR --exit-zero
+          python -m flake8 --output-file=flake8-report.txt $MOD_DIR --exit-zero --ignore W503
           sed -i 's|\.\./current-module/||g' flake8-report.txt
           
-          python -m flake8 $MOD_DIR
+          python -m flake8 $MOD_DIR --ignore W503
       - name: Flake8 results upload
         if: success() || failure()
         uses: actions/upload-artifact@v4
@@ -504,7 +413,7 @@ jobs:
           path: ./openimis/flake8-report.txt
   sonar_scan:
     name: Run Sonar Scan
-    runs-on: ubuntu-20.04
+    runs-on: ubuntu-24.04
     needs: [ci_module_psql_test, flake-8-linter]
     if: always()
     env:
