Develop changes

diff --git a/.github/workflows/ci_module.yml b/.github/workflows/ci_module.yml
--- a/.github/workflows/ci_module.yml
+++ b/.github/workflows/ci_module.yml
@@ -33,20 +33,25 @@ on:
         required: false
         type: string
 
+      branchName:
+        required: false
+        type: string
+        default: 'develop'
+
 jobs:
   build_backend:
     name: Build Backend
     runs-on: ubuntu-20.04
     steps:
-      - name: Set up Python 3.8
+      - name: Set up Python 3.10
         uses: actions/setup-python@v2
         with:
-          python-version: 3.8
+          python-version: '3.10'
 
       - name: Pull openIMIS Backend
         run: |
           rm ./openimis -rf
-          git clone --depth=1 --branch=moldova https://github.com/openimis/openimis-be_py.git ./openimis
+          git clone --depth=1 --branch=implementation/moldova/develop https://github.com/openimis/openimis-be_py.git ./openimis
 
       - name: Copy Current branch
         uses: actions/checkout@v2
@@ -79,15 +84,15 @@ jobs:
           echo "MODULE_NAME=$MODULE_NAME" >> $GITHUB_ENV
           
           # Add or replace MODULE_NAME module in openimis.json (local version)
-          echo $(jq --arg name "$MODULE_NAME" 'if [.modules[].name  ==  ($name)]| max then (.modules[]  | select(.name == ($name)) | .pip)|="-e ../current-module" else .modules |= .+ [{name:($name), pip:"../current-module"}] end' openimis.json)  > openimis.json
+          echo $(jq --arg name "$MODULE_NAME" 'if [.modules[].name  ==  ($name)]| max then (.modules[]  | select(.name == ($name)) | .pip)|="-e ../../current-module" else .modules |= .+ [{name:($name), pip:"../../current-module"}] end' openimis.json)  > openimis.json
           cat openimis.json
 
       - name: Install Python dependencies
-        working-directory: ./openimis
+        working-directory: ./openimis/script
         run: |
           python -m pip install --upgrade pip
-          pip install -r requirements.txt
-          python modules-requirements.py openimis.json > modules-requirements.txt
+          pip install -r ../requirements.txt
+          python modules-requirements.py ../openimis.json > modules-requirements.txt
           cat modules-requirements.txt
           pip install --no-cache-dir -r modules-requirements.txt
 
@@ -118,7 +123,7 @@ jobs:
           name: code-artifacts
           path: openimis.tar.gz
   ci_module_mssql_tests:
-    name: Run All Tests (MSSQL)
+    name: Run Module Tests (MSSQL)
     runs-on: ubuntu-20.04
     needs: build_backend
     services:
@@ -137,10 +142,10 @@ jobs:
           --health-retries=10
           --health-cmd="/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P ${SA_PASSWORD} -Q 'SELECT 1' || exit 1"
     steps:
-      - name: Set up Python 3.8
+      - name: Set up Python 3.10
         uses: actions/setup-python@v2
         with:
-          python-version: 3.8
+          python-version: '3.10'
 
       - name: Download site-packages artifact
         uses: actions/download-artifact@v2
@@ -167,7 +172,7 @@ jobs:
         run: |
           export DB_NAME_TEST="test_$DB_NAME"
           
-          if [ ${GITHUB_REF##*/} = "develop" ]; then export DBBRANCH="main"; else export DBBRANCH="develop"; fi
+          if [ ${GITHUB_REF##*/} = "main" ]; then export DBBRANCH="main"; else export DBBRANCH="develop"; fi
           echo "Branch ${GITHUB_REF##*/}, usign ${DBBRANCH} branch for database"
           git clone --depth=1 --branch=$DBBRANCH https://github.com/openimis/database_ms_sqlserver.git ./sql_mssql
           cd sql_mssql/ && bash concatenate_files.sh && cd ..
@@ -199,21 +204,29 @@ jobs:
             ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
             ${{ runner.os }}-pip-
             ${{ runner.os }}-
-      - name: Django tests MSSQL
+      - name: Django tests MSSQL Module
         working-directory: ./openimis/openIMIS
         # Run the tests regardless if previous steps failed (if setup fails the tests should crash instantly)
         if: success() || failure()
         run: |
           python -V
           export MODULES=$(jq -r '(.modules[].name)' ../openimis.json | xargs)
+<<<<<<< HEAD
           # Remove api_fhir_r4 from MODULES
           MODULES=$(echo "$MODULES" | sed 's/api_fhir_r4//g' | xargs)
           echo $MODULES
           pip freeze | grep openimis
           python manage.py test --debug-mode --timing --keepdb $MODULES
+=======
+          MODULES=$(echo "$MODULES" | sed -E "s/\b$(echo "${CI_EXCLUDED_MODULE// /\\b|\\b}")\b/ /g" | xargs)
+          
+          export MODULE_NAME="$(echo $GITHUB_REPOSITORY | sed 's#^openimis/openimis-be-\(.*\)_py$#\1#')"
+          echo "MODULE_NAME=$MODULE_NAME" >> $GITHUB_ENV
+          
+          python manage.py test --debug-mode --timing --keepdb $MODULE_NAME
+>>>>>>> develop
         env:
           SECRET_KEY: secret
-          DEBUG: true
           DB_ENGINE: mssql
           #DJANGO_SETTINGS_MODULE: hat.settings
           DB_HOST: localhost
@@ -224,6 +237,112 @@ jobs:
           #DEV_SERVER: true
           SITE_ROOT: api
           #REMOTE_USER_AUTHENTICATION: False
+          CI_EXCLUDED_MODULE: ${{ vars.CI_EXCLUDED_MODULE }}
+          MODE: DEV
+  ci_module_psql_test_module_only:
+    name: Run Module Tests (PSQL)
+    runs-on: ubuntu-20.04
+    needs: build_backend
+    services:
+      pgsql:
+        image: postgres
+        env:
+          DB_HOST: localhost
+          DB_PORT: 5432
+          POSTGRES_DB: test_imis
+          POSTGRES_USER: postgres
+          POSTGRES_PASSWORD: GitHub999
+        ports:
+          - 5432:5432
+        options: >-
+          --health-cmd pg_isready
+          --health-interval 10s
+          --health-timeout 5s
+          --health-retries 10
+    steps:
+      - name: Set up Python 3.10
+        uses: actions/setup-python@v2
+        with:
+          python-version: '3.10'
+
+      - name: Download site-packages artifact
+        uses: actions/download-artifact@v2
+        with:
+          name: site-packages
+          path: /tmp/
+
+      - name: Locate site-packages
+        run: |
+          SITE_PACKAGES=$(python -c "from distutils.sysconfig import get_python_lib; print(get_python_lib())")
+          echo "SITE_PACKAGES=$SITE_PACKAGES" >> $GITHUB_ENV
+
+      - name: Download site-packages artifact
+        uses: actions/download-artifact@v2
+        with:
+          name: code-artifacts
+          path: /tmp/
+
+      - name: Decompress artifacts
+        run: |
+          sudo tar -xzf /tmp/site-packages.tar.gz -C ${{ env.SITE_PACKAGES }}
+          sudo tar -xzf /tmp/openimis.tar.gz -C .
+      - name: Initialize PSQL
+        run: |
+          export DB_NAME_TEST="test_$DB_NAME"
+
+          if [ ${GITHUB_REF##*/} = "main" ]; then export DBBRANCH="main"; else export DBBRANCH="develop"; fi
+          echo "Branch ${GITHUB_REF##*/}, usign ${DBBRANCH} branch for database"
+          git clone  --depth=1 --branch=$DBBRANCH https://github.com/openimis/database_postgresql.git ./sql_psql
+
+          echo 'set search_path to public' >> ~/.psqlrc
+          PGPASSWORD=GitHub999 psql -U $DB_USER -h $DB_HOST -c "DROP DATABASE IF EXISTS \"$DB_NAME_TEST\";"
+          PGPASSWORD=GitHub999 psql -U $DB_USER -h $DB_HOST -c "CREATE DATABASE \"$DB_NAME_TEST\";"
+
+          PGPASSWORD=GitHub999 psql -U $DB_USER -h $DB_HOST -d $DB_NAME_TEST -f  ./sql_psql/database\ scripts/00_dump.sql | grep . | uniq -c
+          PGPASSWORD=GitHub999 psql -U $DB_USER -h $DB_HOST -d $DB_NAME_TEST -f  ./sql_psql/database\ scripts/02_aux_functions.sql | grep . | uniq -c
+          PGPASSWORD=GitHub999 psql -U $DB_USER -h $DB_HOST -d $DB_NAME_TEST -f  ./sql_psql/database\ scripts/03_views.sql | grep . | uniq -c
+          PGPASSWORD=GitHub999 psql -U $DB_USER -h $DB_HOST -d $DB_NAME_TEST -f  ./sql_psql/database\ scripts/04_functions.sql | grep . | uniq -c
+          PGPASSWORD=GitHub999 psql -U $DB_USER -h $DB_HOST -d $DB_NAME_TEST -f  ./sql_psql/database\ scripts/05_stored_procs.sql | grep . | uniq -c
+          PGPASSWORD=GitHub999 psql -U $DB_USER -h $DB_HOST -d $DB_NAME_TEST -f  ./sql_psql/database\ scripts/demo_db.sql | grep . | uniq -c
+
+        env:
+          DB_HOST: localhost
+          DB_PORT: 5432
+          DB_NAME: imis
+          DB_USER: postgres
+          DB_PASSWORD: GitHub999
+      - name: Django tests PSQL
+        working-directory: ./openimis/openIMIS
+        # Run the tests regardless if previous steps failed (if setup fails the tests should crash instantly)
+        if: success() || failure()
+        run: |
+          export DB_NAME_TEST="test_$DB_NAME"
+          
+          export MODULES=$(jq -r '(.modules[].name)' ../openimis.json | xargs)
+
+          # Remove some module from MODULES
+          MODULES=$(echo "$MODULES" | sed -E "s/\b$(echo "${CI_EXCLUDED_MODULE// /\\b|\\b}")\b/ /g" | xargs)
+          echo $MODULES
+          
+          DB_NAME=test_imis python manage.py migrate
+          # Generate sonar report 
+          export MODULE_NAME="$(echo $GITHUB_REPOSITORY | sed 's#^openimis/openimis-be-\(.*\)_py$#\1#')"
+
+          # This has to exit 0, or report is not generated 
+          python -m coverage run --omit=*/migrations/* ./manage.py test --keepdb $MODULE_NAME
+        env:
+          SECRET_KEY: secret
+          DB_ENGINE: django.db.backends.postgresql
+          #DJANGO_SETTINGS_MODULE: hat.settings
+          DB_HOST: localhost
+          DB_PORT: 5432
+          DB_NAME: imis
+          DB_USER: postgres
+          DB_PASSWORD: GitHub999
+          #DEV_SERVER: true
+          SITE_ROOT: api
+          CI_EXCLUDED_MODULE: ${{ vars.CI_EXCLUDED_MODULE }}
+          MODE: DEV
   ci_module_psql_test:
     name: Run All Tests (PSQL)
     runs-on: ubuntu-20.04
@@ -245,10 +364,10 @@ jobs:
           --health-timeout 5s
           --health-retries 10
     steps:
-      - name: Set up Python 3.8
+      - name: Set up Python 3.10
         uses: actions/setup-python@v2
         with:
-          python-version: 3.8
+          python-version: '3.10'
 
       - name: Download site-packages artifact
         uses: actions/download-artifact@v2
@@ -275,7 +394,7 @@ jobs:
         run: |
           export DB_NAME_TEST="test_$DB_NAME"
           
-          if [ ${GITHUB_REF##*/} = "develop" ]; then export DBBRANCH="main"; else export DBBRANCH="develop"; fi
+          if [ ${GITHUB_REF##*/} = "main" ]; then export DBBRANCH="main"; else export DBBRANCH="develop"; fi
           echo "Branch ${GITHUB_REF##*/}, usign ${DBBRANCH} branch for database"
           git clone  --depth=1 --branch=$DBBRANCH https://github.com/openimis/database_postgresql.git ./sql_psql
           
@@ -296,6 +415,7 @@ jobs:
           DB_NAME: imis
           DB_USER: postgres
           DB_PASSWORD: GitHub999
+          MODE: DEV
       - name: Django tests PSQL
         working-directory: ./openimis/openIMIS
         # Run the tests regardless if previous steps failed (if setup fails the tests should crash instantly)
@@ -304,17 +424,17 @@ jobs:
           python -V
           export MODULES=$(jq -r '(.modules[].name)' ../openimis.json | xargs)
 
-          # Remove api_fhir_r4 from MODULES
-          MODULES=$(echo "$MODULES" | sed 's/api_fhir_r4//g' | xargs)
+          # Remove some module from MODULES
+          MODULES=$(echo "$MODULES" | sed -E "s/\b$(echo "${CI_EXCLUDED_MODULE// /\\b|\\b}")\b/ /g" | xargs)
           echo $MODULES
           # Generate sonar report 
           export MODULE_NAME="$(echo $GITHUB_REPOSITORY | sed 's#^openimis/openimis-be-\(.*\)_py$#\1#')"
           
           # This has to exit 0, or report is not generated 
+          DB_NAME=test_imis python manage.py migrate
           python -m coverage run --source=$MODULE_NAME --omit=*/migrations/* ./manage.py test --keepdb $MODULES
         env:
           SECRET_KEY: secret
-          DEBUG: true
           DB_ENGINE: django.db.backends.postgresql
           #DJANGO_SETTINGS_MODULE: hat.settings
           DB_HOST: localhost
@@ -324,6 +444,8 @@ jobs:
           DB_PASSWORD: GitHub999
           #DEV_SERVER: true
           SITE_ROOT: api
+          CI_EXCLUDED_MODULE: ${{ vars.CI_EXCLUDED_MODULE }}
+          MODE: DEV
       - name: Generate Coverage Report
         if: always()
         working-directory: ./openimis/openIMIS
@@ -348,10 +470,10 @@ jobs:
     runs-on: ubuntu-20.04
     needs: build_backend
     steps:
-      - name: Set up Python 3.8
+      - name: Set up Python 3.10
         uses: actions/setup-python@v2
         with:
-          python-version: 3.8
+          python-version: '3.10'
       - name: Download site-packages artifact
         uses: actions/download-artifact@v2
         with:
@@ -401,7 +523,7 @@ jobs:
       SONAR_ORGANIZATION: ${{ inputs.SONAR_ORGANIZATION }}
       SONAR_PROJECT_NAME: ${{ inputs.SONAR_PROJECT_NAME }}
       SONAR_PROJECT_VERSION: ${{ inputs.SONAR_PROJECT_VERSION }}
-      SONAR_PYTHON_VERSION: 3.8
+      SONAR_PYTHON_VERSION: '3.10'
       SONAR_FLAKE8_REPORT_PATHS: ../report/flake8-report.txt
       SONAR_SOURCES: ${{ inputs.SONAR_SOURCES }}
     steps:
@@ -453,7 +575,7 @@ jobs:
             -Dsonar.organization=${{ inputs.SONAR_ORGANIZATION }}
             -Dsonar.projectName=${{ inputs.SONAR_PROJECT_NAME }}
             -Dsonar.projectVersion=${{ env.SONAR_PROJECT_VERSION }}
-            -Dsonar.python.version=3.8
+            -Dsonar.python.version=3.10
             -Dsonar.sources=current-module
             -Dsonar.python.coverage.reportPaths=report/coverage1.xml,report/coverage2.xml
             -Dsonar.python.flake8.reportPaths=report/flake8-report.txt
