test to raise warning only

diff --git a/.github/workflows/ci_module.yml b/.github/workflows/ci_module.yml
--- a/.github/workflows/ci_module.yml
+++ b/.github/workflows/ci_module.yml
@@ -74,6 +74,11 @@ jobs:
           export MODULE_NAME="$(echo $GITHUB_REPOSITORY | sed 's#^openimis/openimis-be-\(.*\)_py$#\1#')"
           
           echo "MODULE_NAME=$MODULE_NAME" >> $GITHUB_ENV
+
+          export MODULES=$(jq -r '(.modules[].name)' ../openimis.json | xargs)
+          # Remove some module from MODULES
+          MODULES=$(echo "$MODULES" | sed -E "s/\b$(echo "${CI_EXCLUDED_MODULE// /\\b|\\b}")\b/ /g" | xargs)
+          echo "MODULES=$MODULES" >> $GITHUB_ENV
           
           # Add or replace MODULE_NAME module in openimis.json (local version)
           echo $(jq --arg name "$MODULE_NAME" 'if [.modules[].name  ==  ($name)]| max then (.modules[]  | select(.name == ($name)) | .pip)|="-e ../current-module" else .modules |= .+ [{name:($name), pip:"../current-module"}] end' openimis.json)  > openimis.json
@@ -202,10 +207,7 @@ jobs:
         if: success() || failure()
         run: |
           python -V
-          export MODULES=$(jq -r '(.modules[].name)' ../openimis.json | xargs)
-          MODULES=$(echo "$MODULES" | sed -E "s/\b$(echo "${CI_EXCLUDED_MODULE// /\\b|\\b}")\b/ /g" | xargs)
-          echo $MODULES
-          python manage.py test --debug-mode --timing --keepdb $MODULES
+          python manage.py test --debug-mode --timing --keepdb $MODULE_NAME
         env:
           SECRET_KEY: secret
           MODE: DEV
@@ -298,16 +300,8 @@ jobs:
         if: success() || failure()
         run: |
           python -V
-          export MODULES=$(jq -r '(.modules[].name)' ../openimis.json | xargs)
-
-          # Remove some module from MODULES
-          MODULES=$(echo "$MODULES" | sed -E "s/\b$(echo "${CI_EXCLUDED_MODULE// /\\b|\\b}")\b/ /g" | xargs)
-          echo $MODULES
-          # Generate sonar report 
-          export MODULE_NAME="$(echo $GITHUB_REPOSITORY | sed 's#^openimis/openimis-be-\(.*\)_py$#\1#')"
-          
           # This has to exit 0, or report is not generated 
-          python -m coverage run --source=$MODULE_NAME --omit=*/migrations/* ./manage.py test --keepdb $MODULES
+          python -m coverage run --source=$MODULE_NAME --omit=*/migrations/* ./manage.py test --keepdb $MODULE_NAME
         env:
           SECRET_KEY: secret
           MODE: DEV
@@ -321,6 +315,33 @@ jobs:
           #DEV_SERVER: true
           SITE_ROOT: api
           CI_EXCLUDED_MODULE: ${{ vars.CI_EXCLUDED_MODULE }}
+      - name: Django full PSQL
+        working-directory: ./openimis/openIMIS
+        # Run the tests regardless if previous steps failed (if setup fails the tests should crash instantly)
+        if: success() || failure()
+        run: python manage.py test --debug-mode --timing --keepdb $MODULES
+        env:
+          SECRET_KEY: secret
+          MODE: DEV
+          DB_ENGINE: django.db.backends.postgresql
+          #DJANGO_SETTINGS_MODULE: hat.settings
+          DB_HOST: localhost
+          DB_PORT: 5432
+          DB_NAME: imis
+          DB_USER: postgres
+          DB_PASSWORD: GitHub999
+          #DEV_SERVER: true
+          SITE_ROOT: api
+          CI_EXCLUDED_MODULE: ${{ vars.CI_EXCLUDED_MODULE }}
+      # Check if the full test failed but not the PSQL
+      - name: Set warning status if full test step failed
+        id: check-status
+        run: echo ::set-output name=status::${{ job.status != 'success' && steps.django-full-psql.outcome == 'failure' && steps.django-test-psql.outcome == 'success' }}
+      # Print a warning message if the previous step failed
+      - name: Print warning
+        if: steps.check-status.outputs.status == 'true'
+        run: echo "Global test failed, check if it is not because of your changes"
+
       - name: Generate Coverage Report
         if: always()
         working-directory: ./openimis/openIMIS
@@ -376,7 +397,6 @@ jobs:
         if: success() || failure()
         run: |
           # Flake8 Report
-          export MODULE_NAME="$(echo $GITHUB_REPOSITORY | sed 's#^openimis/openimis-be-\(.*\)_py$#\1#')"
           MOD_DIR="../current-module/$MODULE_NAME"
           python -m flake8 --output-file=flake8-report.txt $MOD_DIR --exit-zero
           sed -i 's|\.\./current-module/||g' flake8-report.txt
