PSQL Tests as separate job

diff --git a/.github/workflows/ci_module.yml b/.github/workflows/ci_module.yml
--- a/.github/workflows/ci_module.yml
+++ b/.github/workflows/ci_module.yml
@@ -151,40 +151,15 @@ jobs:
           name: code-artifacts
           path: ./
 
-      - name: Django tests PSQL
-        working-directory: ./openimis/openIMIS
-        # Run the tests regardless if previous steps failed (if setup fails the tests should crash instantly)
-        if: success() || failure()
-        run: |
-          python -V
-          export MODULES=$(jq -r '(.modules[].name)' ../openimis.json | xargs)
-          echo $MODULES
-          python manage.py test --keepdb $MODULES
-          # Generate sonar report 
-          coverage run --source=$MODULES --omit=*/migrations/* ./manage.py test --keepdb $MODULES
-          coverage xml -o coverage.xml
-        env:
-          SECRET_KEY: secret
-          DEBUG: true
-          DB_ENGINE: django.db.backends.postgresql
-          #DJANGO_SETTINGS_MODULE: hat.settings
-          DB_HOST: localhost
-          DB_PORT: 5432
-          DB_NAME: imis
-          DB_USER: postgres
-          DB_PASSWORD: GitHub999
-          #DEV_SERVER: true
-          SITE_ROOT: api
-
-      - name: Flake8 Style Check
-        working-directory: ./openimis/openIMIS
-        # Run the tests regardless if previous steps failed (if setup fails the tests should crash instantly)
-        if: success() || failure()
-        run: |
-          # Flake8 Report 
-          export MODULE_NAME="$(echo $GITHUB_REPOSITORY | sed 's#^openimis/openimis-be-\(.*\)_py$#\1#')"
-          MOD_DIR="../../current-module/${$MODULE_NAME}
-          flake8 --append-config=../.flake8 --output-file=flake8-report.txt $MOD_DIR
+#      - name: Flake8 Style Check
+#        working-directory: ./openimis/openIMIS
+#        # Run the tests regardless if previous steps failed (if setup fails the tests should crash instantly)
+#        if: success() || failure()
+#        run: |
+#          # Flake8 Report
+#          export MODULE_NAME="$(echo $GITHUB_REPOSITORY | sed 's#^openimis/openimis-be-\(.*\)_py$#\1#')"
+#          MOD_DIR="../../current-module/${$MODULE_NAME}
+#          flake8 --append-config=../.flake8 --output-file=flake8-report.txt $MOD_DIR
 
   ci_module_mssql_tests:
     runs-on: ubuntu-20.04
@@ -217,6 +192,34 @@ jobs:
           #DEV_SERVER: true
           SITE_ROOT: api
           #REMOTE_USER_AUTHENTICATION: False
-#  ci_module_mssql_test:
+  ci_module_psql_test:
+    - name: Download build artifacts
+      uses: actions/download-artifact@v2
+      with:
+        name: code-artifacts
+    - name: Django tests PSQL
+      working-directory: ./openimis/openIMIS
+      # Run the tests regardless if previous steps failed (if setup fails the tests should crash instantly)
+      if: success() || failure()
+      run: |
+        python -V
+        export MODULES=$(jq -r '(.modules[].name)' ../openimis.json | xargs)
+        echo $MODULES
+        python manage.py test --keepdb $MODULES
+        # Generate sonar report 
+        coverage run --source=$MODULES --omit=*/migrations/* ./manage.py test --keepdb $MODULES
+        coverage xml -o coverage.xml
+      env:
+        SECRET_KEY: secret
+        DEBUG: true
+        DB_ENGINE: django.db.backends.postgresql
+        #DJANGO_SETTINGS_MODULE: hat.settings
+        DB_HOST: localhost
+        DB_PORT: 5432
+        DB_NAME: imis
+        DB_USER: postgres
+        DB_PASSWORD: GitHub999
+        #DEV_SERVER: true
+        SITE_ROOT: api
 #  ci_module_flake8:
 #  ci_module_sonar:
