Fixed syntax

diff --git a/.github/workflows/ci_module.yml b/.github/workflows/ci_module.yml
--- a/.github/workflows/ci_module.yml
+++ b/.github/workflows/ci_module.yml
@@ -7,39 +7,6 @@ on:
 jobs:
   ci_module_build:
     runs-on: ubuntu-20.04
-
-    services:
-      mssql:
-        image: mcr.microsoft.com/mssql/server:2017-latest
-        env:
-          ACCEPT_EULA: Y
-          SA_PASSWORD: GitHub999
-        ports:
-          - 1433:1433
-        # this health-cmd needed because the mssql container does not provide a health check
-        options: >-
-          --health-interval=10s
-          --health-timeout=5s
-          --health-start-period=10s
-          --health-retries=10
-          --health-cmd="/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P ${SA_PASSWORD} -Q 'SELECT 1' || exit 1"
-      
-      pgsql:
-        image: postgres
-        env:
-          DB_HOST: localhost
-          DB_PORT: 5432
-          POSTGRES_DB: imis
-          POSTGRES_USER: postgres
-          POSTGRES_PASSWORD: GitHub999
-        ports:
-          - 5432:5432
-        options: >-
-          --health-cmd pg_isready
-          --health-interval 10s
-          --health-timeout 5s
-          --health-retries 10
-
     steps:
       - name: Set up Python 3.8
         uses: actions/setup-python@v2
@@ -91,32 +58,45 @@ jobs:
         run: |
           pip list
 
-      - name: Initialize PSQL
-        run: |
-          export DB_NAME_TEST="test_$DB_NAME"
+      - name: Upload build artifacts
+        uses: actions/upload-artifact@v2
+        with:
+          name: code-artifacts
+          path: ./
 
-          if [ ${GITHUB_REF##*/} = "develop" ]; then export DBBRANCH="main"; else export DBBRANCH="develop"; fi
-          echo "Branch ${GITHUB_REF##*/}, usign ${DBBRANCH} branch for database"
-          git clone  --depth=1 --branch=$DBBRANCH https://github.com/openimis/database_postgresql.git ./sql_psql
+#      - name: Flake8 Style Check
+#        working-directory: ./openimis/openIMIS
+#        # Run the tests regardless if previous steps failed (if setup fails the tests should crash instantly)
+#        if: success() || failure()
+#        run: |
+#          # Flake8 Report
+#          export MODULE_NAME="$(echo $GITHUB_REPOSITORY | sed 's#^openimis/openimis-be-\(.*\)_py$#\1#')"
+#          MOD_DIR="../../current-module/${$MODULE_NAME}
+#          flake8 --append-config=../.flake8 --output-file=flake8-report.txt $MOD_DIR
 
-          echo 'set search_path to public' >> ~/.psqlrc
-          PGPASSWORD=GitHub999 psql -U $DB_USER -h $DB_HOST -c "DROP DATABASE IF EXISTS \"$DB_NAME_TEST\";"
-          PGPASSWORD=GitHub999 psql -U $DB_USER -h $DB_HOST -c "CREATE DATABASE \"$DB_NAME_TEST\";"
-
-          PGPASSWORD=GitHub999 psql -U $DB_USER -h $DB_HOST -d $DB_NAME_TEST -f  ./sql_psql/database\ scripts/00_dump.sql | grep . | uniq -c
-          PGPASSWORD=GitHub999 psql -U $DB_USER -h $DB_HOST -d $DB_NAME_TEST -f  ./sql_psql/database\ scripts/02_aux_functions.sql | grep . | uniq -c
-          PGPASSWORD=GitHub999 psql -U $DB_USER -h $DB_HOST -d $DB_NAME_TEST -f  ./sql_psql/database\ scripts/03_views.sql | grep . | uniq -c
-          PGPASSWORD=GitHub999 psql -U $DB_USER -h $DB_HOST -d $DB_NAME_TEST -f  ./sql_psql/database\ scripts/04_functions.sql | grep . | uniq -c
-          PGPASSWORD=GitHub999 psql -U $DB_USER -h $DB_HOST -d $DB_NAME_TEST -f  ./sql_psql/database\ scripts/05_stored_procs.sql | grep . | uniq -c
-          PGPASSWORD=GitHub999 psql -U $DB_USER -h $DB_HOST -d $DB_NAME_TEST -f  ./sql_psql/database\ scripts/demo_db.sql | grep . | uniq -c
-
+  ci_module_mssql_tests:
+    runs-on: ubuntu-20.04
+    needs: ci_module_build
+    services:
+      mssql:
+        image: mcr.microsoft.com/mssql/server:2017-latest
         env:
-          DB_HOST: localhost
-          DB_PORT: 5432
-          DB_NAME: imis
-          DB_USER: postgres
-          DB_PASSWORD: GitHub999
-
+          ACCEPT_EULA: Y
+          SA_PASSWORD: GitHub999
+        ports:
+          - 1433:1433
+        # this health-cmd needed because the mssql container does not provide a health check
+        options: >-
+          --health-interval=10s
+          --health-timeout=5s
+          --health-start-period=10s
+          --health-retries=10
+          --health-cmd="/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P ${SA_PASSWORD} -Q 'SELECT 1' || exit 1"
+    steps:
+      - name: Download build artifacts
+        uses: actions/download-artifact@v2
+        with:
+          name: code-artifacts
       - name: Initialize MSSQL
         run: |
           export DB_NAME_TEST="test_$DB_NAME"
@@ -144,32 +124,15 @@ jobs:
           DB_NAME: imis
           DB_USER: sa
           DB_PASSWORD: GitHub999
-
-      - name: Upload build artifacts
-        uses: actions/upload-artifact@v2
+      - name: Cache dependencies
+        uses: actions/cache@v2
         with:
-          name: code-artifacts
-          path: ./
-
-#      - name: Flake8 Style Check
-#        working-directory: ./openimis/openIMIS
-#        # Run the tests regardless if previous steps failed (if setup fails the tests should crash instantly)
-#        if: success() || failure()
-#        run: |
-#          # Flake8 Report
-#          export MODULE_NAME="$(echo $GITHUB_REPOSITORY | sed 's#^openimis/openimis-be-\(.*\)_py$#\1#')"
-#          MOD_DIR="../../current-module/${$MODULE_NAME}
-#          flake8 --append-config=../.flake8 --output-file=flake8-report.txt $MOD_DIR
-
-  ci_module_mssql_tests:
-    runs-on: ubuntu-20.04
-    needs: ci_module_build
-    steps:
-      - name: Download build artifacts
-        uses: actions/download-artifact@v2
-        with:
-          name: code-artifacts
-
+          path: ~/.cache/pip
+          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
+          restore-keys: |
+            ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
+            ${{ runner.os }}-pip-
+            ${{ runner.os }}-
       - name: Django tests MSSQL
         working-directory: ./openimis/openIMIS
         # Run the tests regardless if previous steps failed (if setup fails the tests should crash instantly)
@@ -195,11 +158,61 @@ jobs:
   ci_module_psql_test:
     runs-on: ubuntu-20.04
     needs: ci_module_build
+    services:
+      pgsql:
+        image: postgres
+        env:
+          DB_HOST: localhost
+          DB_PORT: 5432
+          POSTGRES_DB: imis
+          POSTGRES_USER: postgres
+          POSTGRES_PASSWORD: GitHub999
+        ports:
+          - 5432:5432
+        options: >-
+          --health-cmd pg_isready
+          --health-interval 10s
+          --health-timeout 5s
+          --health-retries 10
     steps:
       - name: Download build artifacts
         uses: actions/download-artifact@v2
         with:
           name: code-artifacts
+      - name: Cache dependencies
+        uses: actions/cache@v2
+        with:
+          path: ~/.cache/pip
+          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
+          restore-keys: |
+            ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
+            ${{ runner.os }}-pip-
+            ${{ runner.os }}-
+      - name: Initialize PSQL
+        run: |
+          export DB_NAME_TEST="test_$DB_NAME"
+          
+          if [ ${GITHUB_REF##*/} = "develop" ]; then export DBBRANCH="main"; else export DBBRANCH="develop"; fi
+          echo "Branch ${GITHUB_REF##*/}, usign ${DBBRANCH} branch for database"
+          git clone  --depth=1 --branch=$DBBRANCH https://github.com/openimis/database_postgresql.git ./sql_psql
+          
+          echo 'set search_path to public' >> ~/.psqlrc
+          PGPASSWORD=GitHub999 psql -U $DB_USER -h $DB_HOST -c "DROP DATABASE IF EXISTS \"$DB_NAME_TEST\";"
+          PGPASSWORD=GitHub999 psql -U $DB_USER -h $DB_HOST -c "CREATE DATABASE \"$DB_NAME_TEST\";"
+          
+          PGPASSWORD=GitHub999 psql -U $DB_USER -h $DB_HOST -d $DB_NAME_TEST -f  ./sql_psql/database\ scripts/00_dump.sql | grep . | uniq -c
+          PGPASSWORD=GitHub999 psql -U $DB_USER -h $DB_HOST -d $DB_NAME_TEST -f  ./sql_psql/database\ scripts/02_aux_functions.sql | grep . | uniq -c
+          PGPASSWORD=GitHub999 psql -U $DB_USER -h $DB_HOST -d $DB_NAME_TEST -f  ./sql_psql/database\ scripts/03_views.sql | grep . | uniq -c
+          PGPASSWORD=GitHub999 psql -U $DB_USER -h $DB_HOST -d $DB_NAME_TEST -f  ./sql_psql/database\ scripts/04_functions.sql | grep . | uniq -c
+          PGPASSWORD=GitHub999 psql -U $DB_USER -h $DB_HOST -d $DB_NAME_TEST -f  ./sql_psql/database\ scripts/05_stored_procs.sql | grep . | uniq -c
+          PGPASSWORD=GitHub999 psql -U $DB_USER -h $DB_HOST -d $DB_NAME_TEST -f  ./sql_psql/database\ scripts/demo_db.sql | grep . | uniq -c
+
+        env:
+          DB_HOST: localhost
+          DB_PORT: 5432
+          DB_NAME: imis
+          DB_USER: postgres
+          DB_PASSWORD: GitHub999
       - name: Django tests PSQL
         working-directory: ./openimis/openIMIS
         # Run the tests regardless if previous steps failed (if setup fails the tests should crash instantly)
