Update ci_module.yml

diff --git a/.github/workflows/ci_module.yml b/.github/workflows/ci_module.yml
--- a/.github/workflows/ci_module.yml
+++ b/.github/workflows/ci_module.yml
@@ -33,20 +33,25 @@ on:
         required: false
         type: string
 
+      branchName:
+        required: false
+        type: string
+        default: 'develop'
+
 jobs:
   build_backend:
     name: Build Backend
     runs-on: ubuntu-20.04
     steps:
-      - name: Set up Python 3.10
+      - name: Set up Python 3.10.7
         uses: actions/setup-python@v2
         with:
-          python-version: "3.10"
+          python-version: '3.10.7'
 
       - name: Pull openIMIS Backend
         run: |
           rm ./openimis -rf
-          git clone --depth=1 --branch=develop https://github.com/openimis/openimis-be_py.git ./openimis
+          git clone --depth=1 --branch=${{ inputs.branchName }} https://github.com/openimis/openimis-be_py.git ./openimis
 
       - name: Copy Current branch
         uses: actions/checkout@v2
@@ -72,17 +77,14 @@ jobs:
           sudo apt-get install jq
 
           export MODULE_NAME="$(echo $GITHUB_REPOSITORY | sed 's#^openimis/openimis-be-\(.*\)_py$#\1#')"
+          
           echo "MODULE_NAME=$MODULE_NAME" >> $GITHUB_ENV
-          export MODULES=$(jq -r '(.modules[].name)' ./openimis.json | xargs)
-          # Remove some module from MODULES
-          MODULES=$(echo "$MODULES" | sed -E "s/\b$(echo "${CI_EXCLUDED_MODULE// /\\b|\\b}")\b/ /g" | xargs)
-          echo "MODULES=$MODULES" >> $GITHUB_ENV
           
           # Add or replace MODULE_NAME module in openimis.json (local version)
           echo $(jq --arg name "$MODULE_NAME" 'if [.modules[].name  ==  ($name)]| max then (.modules[]  | select(.name == ($name)) | .pip)|="-e ../current-module" else .modules |= .+ [{name:($name), pip:"../current-module"}] end' openimis.json)  > openimis.json
           cat openimis.json
 
-      - name: Install Python dependencies3.10
+      - name: Install Python dependencies
         working-directory: ./openimis
         run: |
           python -m pip install --upgrade pip
@@ -137,10 +139,10 @@ jobs:
           --health-retries=10
           --health-cmd="/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P ${SA_PASSWORD} -Q 'SELECT 1' || exit 1"
     steps:
-      - name: Set up Python 3.10
+      - name: Set up Python 3.10.7
         uses: actions/setup-python@v2
         with:
-          python-version: "3.10"
+          python-version: '3.10.7'
 
       - name: Download site-packages artifact
         uses: actions/download-artifact@v2
@@ -148,13 +150,10 @@ jobs:
           name: site-packages
           path: /tmp/
 
-
       - name: Locate site-packages
         run: |
           SITE_PACKAGES=$(python -c "from distutils.sysconfig import get_python_lib; print(get_python_lib())")
           echo "SITE_PACKAGES=$SITE_PACKAGES" >> $GITHUB_ENV
-          export MODULE_NAME="$(echo $GITHUB_REPOSITORY | sed 's#^openimis/openimis-be-\(.*\)_py$#\1#')"
-          echo "MODULE_NAME=$MODULE_NAME" >> $GITHUB_ENV
 
       - name: Download site-packages artifact
         uses: actions/download-artifact@v2
@@ -208,10 +207,13 @@ jobs:
         if: success() || failure()
         run: |
           python -V
-          python manage.py test --debug-mode --timing --keepdb $MODULE_NAME
+          export MODULES=$(jq -r '(.modules[].name)' ../openimis.json | xargs)
+          MODULES=$(echo "$MODULES" | sed -E "s/\b$(echo "${CI_EXCLUDED_MODULE// /\\b|\\b}")\b/ /g" | xargs)
+          echo $MODULES
+          python manage.py test --debug-mode --timing --keepdb $MODULES
         env:
           SECRET_KEY: secret
-          MODE: DEV
+          DEBUG: true
           DB_ENGINE: mssql
           #DJANGO_SETTINGS_MODULE: hat.settings
           DB_HOST: localhost
@@ -223,6 +225,112 @@ jobs:
           SITE_ROOT: api
           #REMOTE_USER_AUTHENTICATION: False
           CI_EXCLUDED_MODULE: ${{ vars.CI_EXCLUDED_MODULE }}
+          MODE: DEV
+  ci_module_psql_test_module_only:
+    name: Run Module Tests (PSQL)
+    runs-on: ubuntu-20.04
+    needs: build_backend
+    services:
+      pgsql:
+        image: postgres
+        env:
+          DB_HOST: localhost
+          DB_PORT: 5432
+          POSTGRES_DB: test_imis
+          POSTGRES_USER: postgres
+          POSTGRES_PASSWORD: GitHub999
+        ports:
+          - 5432:5432
+        options: >-
+          --health-cmd pg_isready
+          --health-interval 10s
+          --health-timeout 5s
+          --health-retries 10
+    steps:
+      - name: Set up Python 3.10.7
+        uses: actions/setup-python@v2
+        with:
+          python-version: '3.10.7'
+
+      - name: Download site-packages artifact
+        uses: actions/download-artifact@v2
+        with:
+          name: site-packages
+          path: /tmp/
+
+      - name: Locate site-packages
+        run: |
+          SITE_PACKAGES=$(python -c "from distutils.sysconfig import get_python_lib; print(get_python_lib())")
+          echo "SITE_PACKAGES=$SITE_PACKAGES" >> $GITHUB_ENV
+
+      - name: Download site-packages artifact
+        uses: actions/download-artifact@v2
+        with:
+          name: code-artifacts
+          path: /tmp/
+
+      - name: Decompress artifacts
+        run: |
+          sudo tar -xzf /tmp/site-packages.tar.gz -C ${{ env.SITE_PACKAGES }}
+          sudo tar -xzf /tmp/openimis.tar.gz -C .
+      - name: Initialize PSQL
+        run: |
+          export DB_NAME_TEST="test_$DB_NAME"
+
+          if [ ${GITHUB_REF##*/} = "main" ]; then export DBBRANCH="main"; else export DBBRANCH="develop"; fi
+          echo "Branch ${GITHUB_REF##*/}, usign ${DBBRANCH} branch for database"
+          git clone  --depth=1 --branch=$DBBRANCH https://github.com/openimis/database_postgresql.git ./sql_psql
+
+          echo 'set search_path to public' >> ~/.psqlrc
+          PGPASSWORD=GitHub999 psql -U $DB_USER -h $DB_HOST -c "DROP DATABASE IF EXISTS \"$DB_NAME_TEST\";"
+          PGPASSWORD=GitHub999 psql -U $DB_USER -h $DB_HOST -c "CREATE DATABASE \"$DB_NAME_TEST\";"
+
+          PGPASSWORD=GitHub999 psql -U $DB_USER -h $DB_HOST -d $DB_NAME_TEST -f  ./sql_psql/database\ scripts/00_dump.sql | grep . | uniq -c
+          PGPASSWORD=GitHub999 psql -U $DB_USER -h $DB_HOST -d $DB_NAME_TEST -f  ./sql_psql/database\ scripts/02_aux_functions.sql | grep . | uniq -c
+          PGPASSWORD=GitHub999 psql -U $DB_USER -h $DB_HOST -d $DB_NAME_TEST -f  ./sql_psql/database\ scripts/03_views.sql | grep . | uniq -c
+          PGPASSWORD=GitHub999 psql -U $DB_USER -h $DB_HOST -d $DB_NAME_TEST -f  ./sql_psql/database\ scripts/04_functions.sql | grep . | uniq -c
+          PGPASSWORD=GitHub999 psql -U $DB_USER -h $DB_HOST -d $DB_NAME_TEST -f  ./sql_psql/database\ scripts/05_stored_procs.sql | grep . | uniq -c
+          PGPASSWORD=GitHub999 psql -U $DB_USER -h $DB_HOST -d $DB_NAME_TEST -f  ./sql_psql/database\ scripts/demo_db.sql | grep . | uniq -c
+
+        env:
+          DB_HOST: localhost
+          DB_PORT: 5432
+          DB_NAME: imis
+          DB_USER: postgres
+          DB_PASSWORD: GitHub999
+      - name: Django tests PSQL
+        working-directory: ./openimis/openIMIS
+        # Run the tests regardless if previous steps failed (if setup fails the tests should crash instantly)
+        if: success() || failure()
+        run: |
+          export DB_NAME_TEST="test_$DB_NAME"
+          
+          export MODULES=$(jq -r '(.modules[].name)' ../openimis.json | xargs)
+
+          # Remove some module from MODULES
+          MODULES=$(echo "$MODULES" | sed -E "s/\b$(echo "${CI_EXCLUDED_MODULE// /\\b|\\b}")\b/ /g" | xargs)
+          echo $MODULES
+          
+          DB_NAME=test_imis python manage.py migrate
+          # Generate sonar report 
+          export MODULE_NAME="$(echo $GITHUB_REPOSITORY | sed 's#^openimis/openimis-be-\(.*\)_py$#\1#')"
+
+          # This has to exit 0, or report is not generated 
+          python -m coverage run --omit=*/migrations/* ./manage.py test --keepdb $MODULE_NAME
+        env:
+          SECRET_KEY: secret
+          DEBUG: true
+          DB_ENGINE: django.db.backends.postgresql
+          #DJANGO_SETTINGS_MODULE: hat.settings
+          DB_HOST: localhost
+          DB_PORT: 5432
+          DB_NAME: imis
+          DB_USER: postgres
+          DB_PASSWORD: GitHub999
+          #DEV_SERVER: true
+          SITE_ROOT: api
+          CI_EXCLUDED_MODULE: ${{ vars.CI_EXCLUDED_MODULE }}
+          MODE: DEV
   ci_module_psql_test:
     name: Run All Tests (PSQL)
     runs-on: ubuntu-20.04
@@ -244,10 +352,10 @@ jobs:
           --health-timeout 5s
           --health-retries 10
     steps:
-      - name: Set up Python 3.10
+      - name: Set up Python 3.10.7
         uses: actions/setup-python@v2
         with:
-          python-version: "3.10"
+          python-version: '3.10.7'
 
       - name: Download site-packages artifact
         uses: actions/download-artifact@v2
@@ -259,8 +367,6 @@ jobs:
         run: |
           SITE_PACKAGES=$(python -c "from distutils.sysconfig import get_python_lib; print(get_python_lib())")
           echo "SITE_PACKAGES=$SITE_PACKAGES" >> $GITHUB_ENV
-          export MODULE_NAME="$(echo $GITHUB_REPOSITORY | sed 's#^openimis/openimis-be-\(.*\)_py$#\1#')"
-          echo "MODULE_NAME=$MODULE_NAME" >> $GITHUB_ENV
 
       - name: Download site-packages artifact
         uses: actions/download-artifact@v2
@@ -297,42 +403,27 @@ jobs:
           DB_NAME: imis
           DB_USER: postgres
           DB_PASSWORD: GitHub999
+          MODE: DEV
       - name: Django tests PSQL
         working-directory: ./openimis/openIMIS
-        id: django-test-psql
         # Run the tests regardless if previous steps failed (if setup fails the tests should crash instantly)
         if: success() || failure()
         run: |
           python -V
-          # This has to exit 0, or report is not generated 
-          python -m coverage run --source=$MODULE_NAME --omit=*/migrations/* ./manage.py test --keepdb $MODULE_NAME
-        env:
-          SECRET_KEY: secret
-          MODE: DEV
-          DB_ENGINE: django.db.backends.postgresql
-          #DJANGO_SETTINGS_MODULE: hat.settings
-          DB_HOST: localhost
-          DB_PORT: 5432
-          DB_NAME: imis
-          DB_USER: postgres
-          DB_PASSWORD: GitHub999
-          #DEV_SERVER: true
-          SITE_ROOT: api
-          CI_EXCLUDED_MODULE: ${{ vars.CI_EXCLUDED_MODULE }}
-      - name: Django full PSQL
-        working-directory: ./openimis/openIMIS
-        id: django-full-psql
-        # Run the tests regardless if previous steps failed (if setup fails the tests should crash instantly)
-        run: |
           export MODULES=$(jq -r '(.modules[].name)' ../openimis.json | xargs)
+
           # Remove some module from MODULES
           MODULES=$(echo "$MODULES" | sed -E "s/\b$(echo "${CI_EXCLUDED_MODULE// /\\b|\\b}")\b/ /g" | xargs)
-          echo "MODULES=$MODULES" >> $GITHUB_ENV  
-          python manage.py test --debug-mode --timing --keepdb $MODULES
-        continue-on-error: true
+          echo $MODULES
+          # Generate sonar report 
+          export MODULE_NAME="$(echo $GITHUB_REPOSITORY | sed 's#^openimis/openimis-be-\(.*\)_py$#\1#')"
+          
+          # This has to exit 0, or report is not generated 
+          DB_NAME=test_imis python manage.py migrate
+          python -m coverage run --source=$MODULE_NAME --omit=*/migrations/* ./manage.py test --keepdb $MODULES
         env:
           SECRET_KEY: secret
-          MODE: DEV
+          DEBUG: true
           DB_ENGINE: django.db.backends.postgresql
           #DJANGO_SETTINGS_MODULE: hat.settings
           DB_HOST: localhost
@@ -343,14 +434,7 @@ jobs:
           #DEV_SERVER: true
           SITE_ROOT: api
           CI_EXCLUDED_MODULE: ${{ vars.CI_EXCLUDED_MODULE }}
-      # Check if the full test failed but not the PSQL
-      - name: Set warning status if full test step failed
-        id: check-status
-        run: echo "status=${{ steps.django-full-psql.outcome == 'failure' && steps.django-test-psql.outcome == 'success' }}" >> $GITHUB_OUTPUT
-      # Print a warning message if the previous step failed
-      - name: Print warning
-        if: steps.check-status.outputs.status == 'true'
-        run: echo "::warning::Global test failed, check if it is not because of your changes"
+          MODE: DEV
       - name: Generate Coverage Report
         if: always()
         working-directory: ./openimis/openIMIS
@@ -375,10 +459,10 @@ jobs:
     runs-on: ubuntu-20.04
     needs: build_backend
     steps:
-      - name: Set up Python 3.10
+      - name: Set up Python 3.10.7
         uses: actions/setup-python@v2
         with:
-          python-version: "3.10"
+          python-version: '3.10.7'
       - name: Download site-packages artifact
         uses: actions/download-artifact@v2
         with:
@@ -406,6 +490,7 @@ jobs:
         if: success() || failure()
         run: |
           # Flake8 Report
+          export MODULE_NAME="$(echo $GITHUB_REPOSITORY | sed 's#^openimis/openimis-be-\(.*\)_py$#\1#')"
           MOD_DIR="../current-module/$MODULE_NAME"
           python -m flake8 --output-file=flake8-report.txt $MOD_DIR --exit-zero
           sed -i 's|\.\./current-module/||g' flake8-report.txt
@@ -427,7 +512,7 @@ jobs:
       SONAR_ORGANIZATION: ${{ inputs.SONAR_ORGANIZATION }}
       SONAR_PROJECT_NAME: ${{ inputs.SONAR_PROJECT_NAME }}
       SONAR_PROJECT_VERSION: ${{ inputs.SONAR_PROJECT_VERSION }}
-      SONAR_PYTHON_VERSION: "3.10"
+      SONAR_PYTHON_VERSION: '3.10.7'
       SONAR_FLAKE8_REPORT_PATHS: ../report/flake8-report.txt
       SONAR_SOURCES: ${{ inputs.SONAR_SOURCES }}
     steps:
@@ -479,7 +564,7 @@ jobs:
             -Dsonar.organization=${{ inputs.SONAR_ORGANIZATION }}
             -Dsonar.projectName=${{ inputs.SONAR_PROJECT_NAME }}
             -Dsonar.projectVersion=${{ env.SONAR_PROJECT_VERSION }}
-            -Dsonar.python.version="3.10"
+            -Dsonar.python.version=3.10.7
             -Dsonar.sources=current-module
             -Dsonar.python.coverage.reportPaths=report/coverage1.xml,report/coverage2.xml
             -Dsonar.python.flake8.reportPaths=report/flake8-report.txt
